In [29]:
from tensorflow.python.keras.models import load_model
import numpy as np
import pickle

In [2]:
model = load_model('checkpointy_tft_negative.h5')

In [18]:
pairs = [['TFT11_Garen', 'TFT11_Riven'],
         ['TFT11_Yasuo', 'TFT11_Ahri'],
         ['TFT11_Volibear', 'TFT11_Tristana'],
         ['TFT11_Caitlyn', 'TFT11_Illaoi'],
         ['TFT11_Caitlyn', 'TFT11_Senna'],
         ['TFT_Item_InfinityEdge', 'TFT_Item_GuinsoosRageblade'],
         ['TFT_Item_BrambleVest', 'TFT_Item_DragonsClaw'],
         ['TFT_Item_Bloodthirster', 'TFT_Item_TitansResolve'],
         ['TFT_Item_WarmogsArmor', 'TFT_Item_DragonsClaw'],
         ['TFT_Item_WarmogsArmor', 'TFT_Item_BrambleVest'],
         ['TFT11_Bard', 'TFT_Item_GuinsoosRageblade'],
         ['TFT11_Yone', 'TFT_Item_TitansResolve'],
         ['TFT11_Galio', 'TFT_Item_WarmogsArmor']]

In [40]:
word2idx = {}
with open('word2idx.pkl', 'rb') as file:
    word2idx = pickle.load(file)

In [41]:
outcome = []
for i in range(len(pairs)):
    outcome.append(model.predict([np.array([word2idx[pairs[i][0]]]), np.array([word2idx[pairs[i][1]]])]))

In [42]:
outcome

[array([[0.2214134]], dtype=float32),
 array([[0.13933861]], dtype=float32),
 array([[-0.14216518]], dtype=float32),
 array([[0.15321493]], dtype=float32),
 array([[0.34933352]], dtype=float32),
 array([[0.5241101]], dtype=float32),
 array([[0.82593906]], dtype=float32),
 array([[1.1570297]], dtype=float32),
 array([[0.7419531]], dtype=float32),
 array([[0.6927216]], dtype=float32),
 array([[0.98204833]], dtype=float32),
 array([[0.5194949]], dtype=float32),
 array([[-0.3723874]], dtype=float32)]